# Generated by Django 2.2.6 on 2019-12-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('count', models.IntegerField()),
                ('product_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='mahsul',
            name='masul_type',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Mahsul',
        ),
        migrations.DeleteModel(
            name='MahsulType',
        ),
        migrations.AddField(
            model_name='provide',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Provider'),
        ),
        migrations.AddField(
            model_name='provide',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Provider'),
        ),
        migrations.AddField(
            model_name='buy',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Provider'),
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Product'),
        ),
    ]
