# Generated by Django 2.2.6 on 2020-01-21 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockroom', '0002_auto_20191204_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='provide',
            name='person',
        ),
        migrations.RemoveField(
            model_name='provide',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.RenameModel(
            old_name='Provider',
            new_name='Person',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='Provide',
        ),
        migrations.AddField(
            model_name='transaction',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Person'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockroom.Product'),
        ),
    ]
